### ISSUE TITLE
认真写博客中

### ISSUE THREAD

**Issue by xcatliu** [FrankFang/best-chinese-front-end-blogs#1]
不知道我的可不可以：

http://blog.xcatliu.com/

**Comment by FrankFang** [comment]
持续关注中。

**Comment by yalishizhude** [comment]
http://yalishizhude.github.io/
自荐一个~

**Comment by Wscats** [comment]
也推荐一个~ [Good-text-Share](https://github.com/Wscats/Good-text-Share/issues)

**Comment by FrankFang** [comment]
@Wscats   太入门级哈

**Comment by FrankFang** [comment]
已收录 javascript 标签下的文章。  @xcatliu   
个人生活文章较多——这是之前没有收录的原因。
v2ex 在见过你~
