### ISSUE TITLE
蚊子的博客

### ISSUE THREAD

**Issue by wenzi0github** [FrankFang/best-chinese-front-end-blogs#16]
估计 https://www.xiabingbao.com 这样的博客入选不了！

**Comment by FrankFang** [comment]
2018 年只更新了一篇哦，建议一个月至少一篇

**Comment by wenzi0github** [comment]
刚才搜索又搜到这儿了，我的博客还在持续更新，然而这个Git库看着在2018年已经停了，尴尬
