### ISSUE TITLE
关于大搜车的博客地址

### ISSUE THREAD

**Issue by answershuto** [FrankFang/best-chinese-front-end-blogs#18]
方总，我司的新博客地址是 https://blog.souche.com/ ，现在放的还是老的那个。

**Comment by liujiaojiao889** [comment]
你发错了吧




发自网易邮箱大师
在2017年11月15日 09:38，染陌同学 写道：

方总，我司的新博客地址是 https://blog.souche.com/ ，现在放的还是老的那个。

**Comment by answershuto** [comment]
@liujiaojiao889   什么？

**Comment by FrankFang** [comment]
fixed
