### ISSUE TITLE
我觉得还是把公司去掉好一些

### ISSUE THREAD

**Issue by sfengyuan** [FrankFang/best-chinese-front-end-blogs#9]
1. 数据不一定准确.
2. 公司与内容无关
3. 如果博主愿意公开, 它简介里都有, 自己点进去就能看到, 没必要放出来.

**Comment by FrankFang** [comment]
公司可以预示那个人研究的方向，我声明了

> 注：公司信息来自网上公开资料，仅供参考，不保证准确性。
